# DelonixOS — kitty (terminal por omissão)
# Paleta Delonix sobre fundo #0d0f12, a mesma do splash e do SDDM.

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        10.5
adjust_line_height 108%

cursor_shape          beam
cursor_blink_interval 0
scrollback_lines      50000
scrollback_pager      less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

enable_audio_bell    no
window_padding_width 6
hide_window_decorations no
confirm_os_window_close 1
remember_window_size    no
initial_window_width    1100
initial_window_height   700

tab_bar_style          powerline
tab_powerline_style    slanted
tab_bar_min_tabs       2
active_tab_foreground  #0d0f12
active_tab_background  #e0202f
inactive_tab_foreground #8b9099
inactive_tab_background #16191e

# --- cores -------------------------------------------------------------------
foreground            #e6e8ec
background            #0d0f12
selection_foreground  #0d0f12
selection_background  #e0202f
cursor                #e0202f
cursor_text_color     #0d0f12
url_color             #e85a64

# normal
color0  #16191e
color1  #e0202f
color2  #2eb278
color3  #e0a43c
color4  #4a90d9
color5  #8a5cf6
color6  #2ec4b6
color7  #e6e8ec
# bright
color8  #4a5058
color9  #ff4a57
color10 #45d195
color11 #ffc35c
color12 #6aa9e9
color13 #a884ff
color14 #4ee0d2
color15 #ffffff

# --- atalhos -----------------------------------------------------------------
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+t     new_tab_with_cwd
map ctrl+shift+h     show_scrollback
map ctrl+shift+f     launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort
map ctrl+plus        change_font_size all +1.0
map ctrl+minus       change_font_size all -1.0
map ctrl+0           change_font_size all 0

allow_remote_control yes
shell_integration    enabled
